/**
 * Akash compute target — renders a Stack Definition Language (SDL) manifest for the Akash
 * decentralized compute marketplace. Same image as local; the only differences are the orchestrator
 * and that the externally exposed port goes through Akash's HTTP ingress.
 *
 * Streaming-ready: Akash's ingress (NGINX) cuts idle connections at a 60s default — fatal for SSE. We
 * raise `read_timeout`/`send_timeout` and set `next_cases: ["off"]` so long-lived streams survive (the
 * server must still emit bytes — data rows or `:` keepalive comments — to keep the connection warm).
 *
 * The container is STATELESS: it onboards a baked dataset deterministically at boot and serves it, so
 * there's no persistent volume (Akash storage is only lease-scoped anyway). Bigger snapshots ship in
 * the image. Secrets are placeholders here — the operator fills them in (or uses a provider secret).
 */
import type { ComputeProvider, DeployArtifact, DeploySpec } from "./provider";

export const akashCompute: ComputeProvider = {
  target: "akash",
  render(spec: DeploySpec): DeployArtifact {
    const content = `---
# Generated by \`aqueduct deploy --target akash\`. Fill in the CHANGE_ME secrets before deploying.
version: "2.0"
services:
  aqueduct:
    image: ${spec.image}
    env:
      - PORT=${spec.port}
      - AQUEDUCT_DATASET=${spec.dataset}
      - AQUEDUCT_PRIVATE_KEY=CHANGE_ME            # server wallet (receives settlement)
      - AQUEDUCT_RECIPIENT=CHANGE_ME              # payout address (usually the server wallet's)
      - AQUEDUCT_SECRET=CHANGE_ME                 # openssl rand -hex 32
      # - AQUEDUCT_SPONSOR_KEY=CHANGE_ME          # optional distinct gas sponsor
    expose:
      - port: ${spec.port}
        as: 80
        to:
          - global: true
        http_options:
          read_timeout: 3600000                   # SSE-ready: don't cut long streams at the 60s default
          send_timeout: 3600000
          next_cases: ["off"]
profiles:
  compute:
    aqueduct:
      resources:
        cpu:
          units: ${spec.cpu}
        memory:
          size: ${spec.memory}
        storage:
          - size: ${spec.storage}
  placement:
    akash:
      pricing:
        aqueduct:
          denom: uakt
          amount: ${spec.akashPriceUakt}
deployment:
  aqueduct:
    akash:
      profile: aqueduct
      count: 1
`;
    return {
      filename: "akash.deploy.yaml",
      content,
      notes: [
        `docker build -t ${spec.image} . && docker push ${spec.image}   (image must be public/pullable)`,
        "edit akash.deploy.yaml: set AQUEDUCT_PRIVATE_KEY / AQUEDUCT_RECIPIENT / AQUEDUCT_SECRET",
        "provider services akash, or Cloudmos/Console: create deployment from akash.deploy.yaml",
        "CLI: akash tx deployment create akash.deploy.yaml --from <key>  →  create-lease  →  send-manifest",
        "get the URL: akash provider lease-status … (the global:true host) → GET <host>/schema",
        "SSE note: expose a non-80/443 port (raw NodePort) to skip ingress entirely if streams stall",
      ],
    };
  },
};
