/**
 * Local compute target — runs the Tap image via docker-compose. The image is self-contained and
 * portable (permissionless hosting like Akash is a future goal, not yet tested). Secrets come from the
 * operator's shell / .env (compose interpolates `${VAR}`), never baked into the file.
 */
import type { ComputeProvider, DeployArtifact, DeploySpec } from "./provider";

export const localCompute: ComputeProvider = {
  target: "local",
  render(spec: DeploySpec): DeployArtifact {
    const content = `# Generated by \`aqueduct deploy --target local\`.
# Provide secrets via your shell or a .env file next to this compose file:
#   AQUEDUCT_PRIVATE_KEY=0x…   AQUEDUCT_RECIPIENT=0x…   AQUEDUCT_SECRET=$(openssl rand -hex 32)
services:
  aqueduct:
    image: ${spec.image}
    ports:
      - "${spec.port}:${spec.port}"
    environment:
      - PORT=${spec.port}
      - AQUEDUCT_DATASET=${spec.dataset}
      - AQUEDUCT_PRIVATE_KEY=\${AQUEDUCT_PRIVATE_KEY:?set AQUEDUCT_PRIVATE_KEY}
      - AQUEDUCT_RECIPIENT=\${AQUEDUCT_RECIPIENT:?set AQUEDUCT_RECIPIENT}
      - AQUEDUCT_SECRET=\${AQUEDUCT_SECRET:?set AQUEDUCT_SECRET}
      - AQUEDUCT_SPONSOR_KEY=\${AQUEDUCT_SPONSOR_KEY:-}
      - AQUEDUCT_RPC_URL=\${AQUEDUCT_RPC_URL:-}
    restart: unless-stopped
`;
    return {
      filename: "docker-compose.yml",
      content,
      notes: [
        "export AQUEDUCT_PRIVATE_KEY / AQUEDUCT_RECIPIENT / AQUEDUCT_SECRET (or put them in .env)",
        `docker build -t ${spec.image} .`,
        "docker compose up",
        `then: curl localhost:${spec.port}/schema`,
      ],
    };
  },
};
